name: churn-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - scikit-learn
      - tensorflow
      - keras-tuner
      - tensorboard
      - mlflow==2.19.0
      - dagshub
