name: Automated Model Training

on:
  push:
    paths:
      - 'modelling_tuning.py'
      - 'MLproject'
      - 'conda.yaml'
      - '.github/workflows/training.yml'
      - 'get_run_id.py'
  workflow_dispatch:

jobs:
  training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_USERNAME: raflialfansyah
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/raflialfansyah/Bank-Churn-MLflow-msml.mlflow
        run: |
          mlflow run . --env-manager local

      - name: Get latest MLflow run_id
        env:
          MLFLOW_TRACKING_USERNAME: raflialfansyah
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python get_run_id.py

      - name: Install Python dependencies
        run: |
          echo "Semua dependensi Python sudah terinstal di langkah sebelumnya."

      - name: Upload to Google Drive
        uses: actions/upload-artifact@v4
        with:
          name: training-artifacts
          path: tuner_logs/
          
      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_USERNAME: raflialfansyah
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/raflialfansyah/Bank-Churn-MLflow-msml.mlflow
        run: |
          echo "Membangun Docker Container langsung dari model terbaik dengan Run ID: $RUN_ID"
          # Membuat Dockerfile mentah dari MLflow
          mlflow models generate-dockerfile -m "runs:/$RUN_ID/keras_churn_model" -d my_model_docker
          
          # Memperbaiki bug "get-pip.py" Python 3.9 bawaan MLflow secara otomatis!
          sed -i 's|https://bootstrap.pypa.io/get-pip.py|https://bootstrap.pypa.io/pip/3.9/get-pip.py|g' my_model_docker/Dockerfile
          
          # Membangun Docker Image
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bank-churn-model:latest my_model_docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          echo "Image sudah secara otomatis di-tag saat build-docker: ${{ secrets.DOCKERHUB_USERNAME }}/bank-churn-model:latest"

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bank-churn-model:latest
